### PR TITLE
Added drill slot (G85) support

### PR DESCRIPTION
**Pull request by katyo**
Fix issue #3

### CODE REVIEW

**Comment by mcous** [comment]
This is pretty sweet! I appreciate the new test, as well.

One last thing that we talked about in #3: The parser should emit a ["set draw mode to linear interpolation" command](https://github.com/mcous/gerber-parser/blob/master/API.md#set-objects) (`{cmd: 'set', key: 'mode', val: 'int'}`) the first time it sees a slot command. Otherwise, the [plotter](https://github.com/mcous/gerber-plotter) will complain that the interpolation mode has not been set when it gets the interpolate command (options for mode are 'int' for linear, 'cw' for clockwise arc, and 'ccw' for counter-clockwise arc).

**Comment by katyo** [comment]
Of course, I forgot to set an interpolation mode.
As I seen in `_parse-gerber.js` the `val` for linear interpolation mode is 'i' not 'int'.
Is it right?

**Comment by mcous** [comment]
Oops, my mistake! `i` is correct. I confused mode and operation there.

**Comment by katyo** [comment]
Ok. Is it success for now? Is there something yet, which I missed here?

**Comment by mcous** [comment]
Looks good to me! Will have it merged shortly.

**Pull request merged**
